version: '2'

services:
  mysql:
    image: mysql:8.0
    container_name: questions_mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: questions_db
      MYSQL_USER: questions_user
      MYSQL_PASSWORD: questions_password
    ports:
      - "3307:3306"
    volumes:
      - ./backend/internal/db/schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - mysql_data:/var/lib/mysql
    networks:
      - questions_network
    restart: always

  redis:
    image: redis:7.0
    container_name: questions_redis
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    networks:
      - questions_network
    restart: always

networks:
  questions_network:
    driver: bridge

volumes:
  mysql_data:
  redis_data: 